version: '2.4'
services:
  frontend:
    image: kicinskido/frontend
    container_name: frontend
    ports:
      - 5000:5000
    environment:
      - BACKEND_URL=http://backend:5001/ 
  backend:
    image: kicinskido/backend
    container_name: backend
    ports:
      - 5001:5001